---
author: "Adrián & Solveig"
title: "Permutation"
output: html_document
---

```{r}
# Load libraries
library(tidyverse)
```


#Permutation basis:
Mean, define number of permutaions, 10000 being default value.
Define dataset, the column name for the column with the different categories you want to compare means for and the name of the columns with the counts.
The names of the groups/categories.

```{r}
permutation_mean <- function(dataset, name, count, group1, group2, no_perm=10000){
#permute and save difference in mean per round
dataset <- dataset %>% rename("count"=count, "name"=name)
r <- rep(NA,no_perm)  
for (i in 1:length(r)) {
  #shuffle dataset
  p <- cbind(vec1 = dataset$name, count = sample(dataset$count)) %>% 
    as_tibble()
  
  #calculate mean for group 1
  g1 <- p %>% 
    filter(vec1 == group1) %>% 
    summarise(mean(as.numeric(count)))
  
  #calculate mean for group 2
  g2 <- p %>% 
    filter(vec1 == group2) %>% 
    summarise(mean(as.numeric(count))) 
  
  #add difference in mean to vector
  r[i] <- as.numeric(g1) - as.numeric(g2)
  
  if(i%%1000==0) {        #tracker
    cat(i, "\n")
    flush.console()
  }
}

#create df with values for null distribution
pd <- data.frame(i=1:length(r), value=r) %>% 
  tbl_df()

#the observed difference
observed <- (dataset %>% filter(name == group1) %>% summarise(mean(as.numeric(count))))-(dataset %>% filter(name==group2) %>% summarise(mean(as.numeric(count))))

#plotting the null distribution and observed difference with the observed as a line
plot <- ggplot(data = pd, mapping = aes(x=value)) + 
  geom_histogram(fill="darkblue", bins=50) +
  geom_vline(color="darkorange",xintercept = as.numeric(observed)) + 
  xlab("")+
  ylab("Count")+
  theme_minimal()

#permuted p-value. 1 is added because we always expect the next one to be significant (of permuted values)
p_value <- ((sum(abs(r) >= abs(observed[,1]))+1)/(length(r)+1))
return (list(p_value, plot))
}


names <- c(replicate(50,"Something"), replicate(50, "Something_else"))
test <- as.tibble(rnorm(100)) %>% mutate(names=names)

permutation_mean(test, "names", "value", "Something", "Something_else")

```

#Permutation median:

```{r}
permutation_median <- function(dataset, name, count, group1, group2, no_perm=10000, plot=FALSE) {
  #permute and save difference in mean per round
  dataset <- dataset %>% rename("count"=count, "name"=name)
  r <- rep(NA,no_perm)
  
  # Progress bar
  pb <- txtProgressBar(min = 1, max = no_perm, style = 3)
  
  for (i in 1:length(r)) {
    setTxtProgressBar(pb, i)
    #shuffle dataset
    p <- cbind(vec = dataset$name, count = sample(dataset$count)) %>% as_tibble()
  
    #calculate median for group 1 and group 2
    g1 <- p %>% filter(vec == group1) %>% summarise(median(as.numeric(count)))
    g2 <- p %>% filter(vec == group2) %>% summarise(median(as.numeric(count))) 
  
    #add difference in median to vector
    r[i] <- as.numeric(g1) - as.numeric(g2)
  }
  close(pb)

  #create df with values for null distribution
  pd <- data.frame(i=1:length(r), value=r) %>% tbl_df()

  #the observed difference
  observed <- (dataset %>% filter(name == group1) %>%
                summarise(median(as.numeric(count))))-(dataset %>% filter(name==group2) %>%
                summarise(median(as.numeric(count))))

  # If statement to plot or not
  if (plot == TRUE) {
    #plotting the null distribution and observed difference with the observed as a line
    plot <- ggplot(data = pd, mapping = aes(x=value)) + 
      geom_histogram(fill="darkblue", bins=50) +
      geom_vline(color="darkorange",xintercept = as.numeric(observed)) + 
      xlab("")+
      ylab("Count")

    # NICE PRINTING FOR TEST
    # Permuted p-value. 1 is added because we always expect the next one to be significant (of permuted values)
    #
    m1 <- test %>% filter(names == group1) %>% summarise(median(value))
    m2 <- test %>% filter(names == group2) %>% summarise(median(value))
    estimate <- c(as.numeric(m1),as.numeric(m2),as.numeric(observed))
    names(estimate) <- c("Median first group","Median second group","Observed median difference")
    #
    p_value <- ((sum(abs(r) >= abs(observed[,1]))+1)/(length(r)+1))
    names(p_value) <- "p-value"
    #
    result = list(method = "Permutation Test (Median)", p.value = p_value,
                  estimate = estimate,
                  data.name = sprintf("Permutation for group: %s and %s", group1, group2))
    class(result) <- "htest"
    
    print(result)
    return(plot)
  } else if (plot == FALSE) {
    # NICE PRINTING FOR TEST
    # Permuted p-value. 1 is added because we always expect the next one to be significant (of permuted values)
    #
    m1 <- test %>% filter(names == group1) %>% summarise(median(value))
    m2 <- test %>% filter(names == group2) %>% summarise(median(value))
    estimate <- c(as.numeric(m1),as.numeric(m2),as.numeric(observed))
    names(estimate) <- c("Median first group","Median second group","Observed median difference")
    #
    p_value <- ((sum(abs(r) >= abs(observed[,1]))+1)/(length(r)+1))
    names(p_value) <- "p-value"
    #
    result = list(method = "Permutation Test (Median)", p.value = p_value,
                  estimate = estimate,
                  data.name = sprintf("Permutation for group: %s and %s", group1, group2))
    class(result) <- "htest"
    
    print(result)
  }
}

names <- c(replicate(50,"GROUP1"), replicate(50, "GROUP2"))
test <- as.tibble(rnorm(100)) %>% mutate(names=names)

permutation_median(test, "names", "value", "GROUP1", "GROUP2", plot = T)
```

